"""Recompose a no-SY-centred paper ablation suite from existing artifacts.

The revised baseline is an already-generated ``no_sy`` report.  Only the
Strategy and Writer stages are regenerated for the two combined ablations:

* ``no_peer``: no SY and no competitor evidence.
* ``no_subdata``: no SY and primary-data-only domain outputs.

Collection and domain-agent outputs are never regenerated by this runner.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from orchestration.ablation_adapters import run_adapter
from orchestration.ablation_experiment import (
    AblationCondition,
    build_summary,
    code_identity,
    load_condition_result,
    render_summary_markdown,
    run_frozen_final_stage,
)
from orchestration.paths import PROJECT_ROOT


CONDITIONS = {
    "no_peer": AblationCondition(
        "no_peer",
        ("--no-sy", "--no-competitor"),
        "Contribution of competitor evidence when SY is excluded.",
    ),
    "no_subdata": AblationCondition(
        "no_subdata",
        ("--no-sy", "--primary-data-only"),
        "Contribution of secondary context when SY is excluded.",
    ),
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Build the revised no-SY Full/no-peer/no-subdata ablation suite."
    )
    parser.add_argument("--source-suite-root", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--suite-id", required=True)
    parser.add_argument("--replicates", type=int, default=3)
    parser.add_argument("--llm-model", default="gpt-5.4-mini")
    parser.add_argument("--env-file", type=Path, default=PROJECT_ROOT / "configs" / ".env")
    parser.add_argument("--llm-timeout", type=int, default=300)
    parser.add_argument("--max-retries", type=int, default=1)
    parser.add_argument("--semantic-attempts", type=int, default=2)
    parser.add_argument("--final-stage-timeout", type=int, default=900)
    parser.add_argument("--decision-horizon-profile", default="short_term")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--fail-fast", action="store_true")
    return parser


def run_suite(args: argparse.Namespace) -> dict[str, Any]:
    if args.replicates < 1:
        raise ValueError("--replicates must be positive")
    source_root = args.source_suite_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve()
    suite_root = output_root / args.suite_id
    suite_root.mkdir(parents=True, exist_ok=True)
    source_summary = _load_json(source_root / "ablation_summary.json")
    source_rows = {
        (str(row.get("condition") or ""), int(row.get("replicate") or 0)): row
        for row in source_summary.get("runs") or []
        if isinstance(row, dict)
    }
    source_request = source_summary.get("request") if isinstance(source_summary.get("request"), dict) else {}
    company_name = str(source_request.get("company_name") or "")
    selected_date = str(source_request.get("selected_date") or "")
    if not company_name or not selected_date:
        raise ValueError("Source suite is missing company_name or selected_date.")

    audit = _audit_sources(
        source_rows=source_rows,
        replicates=args.replicates,
        company_name=company_name,
    )
    _write_json(suite_root / "source_artifact_audit.json", audit)

    manifest_path = suite_root / "ablation_suite_manifest.json"
    if args.resume and manifest_path.exists():
        manifest = _load_json(manifest_path)
        manifest["status"] = "running"
        manifest["resumed_at"] = _utc_now()
    else:
        manifest = {
            "suite_id": args.suite_id,
            "status": "running",
            "created_at": _utc_now(),
            "project_root": str(PROJECT_ROOT),
            "suite_root": str(suite_root),
            "request": {
                **source_request,
                "llm_model": args.llm_model,
                "replicates": args.replicates,
                "dry_run": bool(args.dry_run),
                "baseline_condition": "full",
                "baseline_definition": "reused prior no_sy output (SY excluded)",
                "conditions": {
                    "full": ["no_sy"],
                    "no_peer": ["no_sy", "no_competitor"],
                    "no_subdata": ["no_sy", "primary_data_only"],
                },
                "source_suite_root": str(source_root),
                "paid_generation_scope": "Strategy and Writer only for no_peer/no_subdata",
            },
            "code": code_identity(),
            "conditions": [
                {
                    "name": "full",
                    "flags": ["--no-sy"],
                    "hypothesis": "Revised Full; prior no_sy report reused byte-for-byte.",
                },
                *[
                    {
                        "name": item.name,
                        "flags": list(item.flags),
                        "hypothesis": item.hypothesis,
                    }
                    for item in CONDITIONS.values()
                ],
            ],
            "runs": [],
        }
    _write_json(manifest_path, manifest)

    for replicate in range(1, args.replicates + 1):
        _upsert_baseline(
            manifest=manifest,
            suite_root=suite_root,
            source_row=source_rows[("no_sy", replicate)],
            replicate=replicate,
            dry_run=args.dry_run,
        )
        _write_json(manifest_path, manifest)

    for name, condition in CONDITIONS.items():
        for replicate in range(1, args.replicates + 1):
            existing = _find_record(manifest, name, replicate)
            if args.resume and existing and existing.get("status") == "success":
                print(f"[revised] SKIP {name}__r{replicate:02d} status=success", flush=True)
                continue
            record = existing if existing is not None else {}
            record.clear()
            condition_root = suite_root / "conditions" / name / f"replicate_{replicate:02d}"
            execution_id = f"{args.suite_id}__{name}__r{replicate:02d}"
            record.update(
                {
                    "condition": name,
                    "replicate": replicate,
                    "attempt": 1,
                    "execution_id": execution_id,
                    "execution_mode": "recomposed_existing_upstream_final_stage",
                    "status": "running",
                    "started_at": _utc_now(),
                    "condition_root": str(condition_root),
                }
            )
            if existing is None:
                manifest["runs"].append(record)
            _write_json(manifest_path, manifest)
            print(f"[revised] START {name}__r{replicate:02d}", flush=True)
            started = time.monotonic()
            try:
                source_manifest, local_steps = _prepare_condition(
                    name=name,
                    condition_root=condition_root,
                    source_rows=source_rows,
                    replicate=replicate,
                    company_name=company_name,
                    selected_date=selected_date,
                    dry_run=args.dry_run,
                )
                record["source_pipeline_manifest"] = str(source_manifest)
                record["local_recomposition_steps"] = local_steps
                record["commands"] = _preview_final_commands(
                    args=args,
                    condition=condition,
                    condition_root=condition_root,
                    source_manifest=source_manifest,
                    company_name=company_name,
                )
                if args.dry_run:
                    returncode = 0
                    pipeline_manifest = None
                    result: dict[str, Any] = {}
                else:
                    frozen = run_frozen_final_stage(
                        args=args,
                        condition=condition,
                        condition_root=condition_root,
                        execution_id=execution_id,
                        source_manifest=source_manifest,
                        log_dir=condition_root / "logs",
                    )
                    returncode = int(frozen["returncode"])
                    pipeline_manifest = Path(str(frozen["manifest_path"]))
                    result = frozen["result"]
                    _assert_final_only_usage(pipeline_manifest)
                record["returncode"] = returncode
                record["pipeline_manifest"] = str(pipeline_manifest or "")
                record["result"] = result
                record["status"] = (
                    "dry_run"
                    if args.dry_run and returncode == 0
                    else "success"
                    if returncode == 0 and result.get("pipeline_status") == "success"
                    else "failed"
                )
            except Exception as exc:  # preserve a resumable suite manifest
                record["returncode"] = 1
                record["status"] = "failed"
                record["error"] = {"type": type(exc).__name__, "message": str(exc)}
            record["elapsed_seconds"] = round(time.monotonic() - started, 3)
            record["completed_at"] = _utc_now()
            _write_json(manifest_path, manifest)
            print(
                f"[revised] END {name}__r{replicate:02d} status={record['status']} "
                f"elapsed={record['elapsed_seconds']}s",
                flush=True,
            )
            if record["status"] == "failed" and args.fail_fast:
                return _finalize(manifest, suite_root)

    return _finalize(manifest, suite_root)


def _audit_sources(
    *,
    source_rows: dict[tuple[str, int], dict[str, Any]],
    replicates: int,
    company_name: str,
) -> dict[str, Any]:
    records: list[dict[str, Any]] = []
    for replicate in range(1, replicates + 1):
        for condition in ("no_sy", "primary_only"):
            row = source_rows.get((condition, replicate))
            if row is None or row.get("status") != "success":
                raise ValueError(f"Missing successful source {condition} replicate {replicate}.")
            manifest_path = Path(str(row.get("pipeline_manifest") or "")).expanduser().resolve()
            manifest = _load_json(manifest_path)
            if manifest.get("status") != "success":
                raise ValueError(f"Source pipeline manifest did not succeed: {manifest_path}")
            outputs = manifest.get("outputs") if isinstance(manifest.get("outputs"), dict) else {}
            root = _pipeline_root(outputs)
            run_key = str(manifest.get("run_key") or "")
            if not run_key.startswith(company_name + "_"):
                raise ValueError(f"Unexpected target run_key in {manifest_path}: {run_key}")
            paths = [manifest_path]
            if condition == "no_sy":
                paths.extend(
                    root / domain / run_key / "final_report.json"
                    for domain in ("Financial", "News", "Y_Finance")
                )
                paths.extend(
                    [
                        Path(str(outputs.get("writer_report") or "")),
                        Path(str(outputs.get("strategy_compact_packet_v2") or "")),
                    ]
                )
            else:
                peer_run_key = str((manifest.get("peer") or {}).get("run_key") or "")
                if not peer_run_key:
                    raise ValueError(f"primary_only source has no peer run_key: {manifest_path}")
                paths.extend(_pre_sy_paths(root, run_key).values())
                peer_paths = _pre_sy_paths(root, peer_run_key)
                paths.extend([peer_paths["financial"], peer_paths["yfinance"]])
                paths.extend(
                    root / "Y_Finance" / source_run_key / "market_full_dataset.csv"
                    for source_run_key in (run_key, peer_run_key)
                )
                paths.append(Path(str(outputs.get("target_config") or "")))
            missing = [str(path) for path in paths if not path.is_file()]
            if missing:
                raise ValueError(f"Missing source artifacts for {condition} r{replicate}: {missing}")
            records.append(
                {
                    "condition": condition,
                    "replicate": replicate,
                    "pipeline_manifest": str(manifest_path),
                    "artifacts": [
                        {"path": str(path.resolve()), "sha256": _sha256(path)} for path in paths
                    ],
                }
            )
    return {
        "status": "pass",
        "created_at": _utc_now(),
        "policy": "existing artifacts only; no collection or domain-agent regeneration",
        "records": records,
    }


def _upsert_baseline(
    *,
    manifest: dict[str, Any],
    suite_root: Path,
    source_row: dict[str, Any],
    replicate: int,
    dry_run: bool,
) -> None:
    existing = _find_record(manifest, "full", replicate)
    if existing and existing.get("status") in {"success", "dry_run"}:
        return
    source_manifest_path = Path(str(source_row["pipeline_manifest"])).expanduser().resolve()
    source = _load_json(source_manifest_path)
    condition_root = suite_root / "conditions" / "full" / f"replicate_{replicate:02d}"
    proxy_path = condition_root / "reused_baseline_manifest.json"
    outputs = source.get("outputs") if isinstance(source.get("outputs"), dict) else {}
    zero_usage = {
        "execution_id": f"{manifest['suite_id']}__full__r{replicate:02d}",
        "expected_cold_cache_logical_calls": 0,
        "observed_logical_calls": 0,
        "transport_attempts": 0,
        "usage": {
            "input_tokens": 0,
            "cached_input_tokens": 0,
            "output_tokens": 0,
            "reasoning_tokens": 0,
            "total_tokens": 0,
        },
        "note": "No calls in revised suite; report reused byte-for-byte from prior no_sy run.",
    }
    proxy = {
        "execution_id": zero_usage["execution_id"],
        "run_key": source.get("run_key"),
        "status": "success",
        "execution_mode": "reused_prior_no_sy_as_revised_full",
        "condition": "full",
        "source_condition": "no_sy",
        "source_pipeline_manifest": str(source_manifest_path),
        "source_report_sha256": _sha256(Path(str(outputs.get("writer_report") or ""))),
        "outputs": outputs,
        "validation": source.get("validation") or {},
        "llm_usage": zero_usage,
        "source_generation_llm_usage": source.get("llm_usage") or {},
        "error": {},
    }
    _write_json(proxy_path, proxy)
    result = load_condition_result(proxy_path)
    record = existing if existing is not None else {}
    record.clear()
    record.update(
        {
            "condition": "full",
            "replicate": replicate,
            "attempt": 1,
            "execution_id": zero_usage["execution_id"],
            "execution_mode": "reused_prior_no_sy_as_revised_full",
            "status": "dry_run" if dry_run else "success",
            "started_at": _utc_now(),
            "completed_at": _utc_now(),
            "elapsed_seconds": 0.0,
            "condition_root": str(condition_root),
            "source_pipeline_manifest": str(source_manifest_path),
            "pipeline_manifest": str(proxy_path),
            "result": result,
        }
    )
    if existing is None:
        manifest["runs"].append(record)


def _prepare_condition(
    *,
    name: str,
    condition_root: Path,
    source_rows: dict[tuple[str, int], dict[str, Any]],
    replicate: int,
    company_name: str,
    selected_date: str,
    dry_run: bool,
) -> tuple[Path, list[dict[str, Any]]]:
    if name == "no_peer":
        path = Path(str(source_rows[("no_sy", replicate)]["pipeline_manifest"])).expanduser().resolve()
        return path, [{"name": "reuse_no_sy_domain_reports", "status": "validated", "api_calls": 0}]
    if name != "no_subdata":
        raise ValueError(f"Unsupported revised condition: {name}")

    primary_manifest_path = Path(
        str(source_rows[("primary_only", replicate)]["pipeline_manifest"])
    ).expanduser().resolve()
    primary = _load_json(primary_manifest_path)
    outputs = primary.get("outputs") if isinstance(primary.get("outputs"), dict) else {}
    source_root = _pipeline_root(outputs)
    run_key = str(primary.get("run_key") or "")
    peer_run_key = str((primary.get("peer") or {}).get("run_key") or "")
    target_config = Path(str(outputs.get("target_config") or "")).expanduser().resolve()
    local_steps: list[dict[str, Any]] = []
    if not dry_run:
        for materialize_run_key in (run_key, peer_run_key):
            domains = ("financial", "news", "yfinance") if materialize_run_key == run_key else ("financial", "yfinance")
            for domain in domains:
                source = _pre_sy_paths(source_root, materialize_run_key)[domain]
                _materialize_no_sy_domain(
                    domain=domain,
                    source=source,
                    output_root=condition_root,
                    run_key=materialize_run_key,
                )
                local_steps.append(
                    {
                        "name": f"no_sy_adapter:{materialize_run_key}:{domain}",
                        "status": "success",
                        "api_calls": 0,
                        "source": str(source),
                        "source_sha256": _sha256(source),
                    }
                )
            market_source = (
                source_root
                / "Y_Finance"
                / materialize_run_key
                / "market_full_dataset.csv"
            )
            market_target = (
                condition_root
                / "Y_Finance"
                / materialize_run_key
                / "market_full_dataset.csv"
            )
            market_target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(market_source, market_target)
            local_steps.append(
                {
                    "name": f"reuse_market_csv:{materialize_run_key}",
                    "status": "success",
                    "api_calls": 0,
                    "source": str(market_source),
                    "source_sha256": _sha256(market_source),
                }
            )
        peer_dir = condition_root / "Competitor" / run_key
        peer_command = [
            sys.executable,
            "-m",
            "Agent_Team.Competitor_Agent.peer_comparison_cli",
            "--target-config",
            str(target_config),
            "--run-key",
            run_key,
            "--company-name",
            company_name,
            "--selected-date",
            selected_date,
            "--peer-run-key",
            peer_run_key,
            "--output-root",
            str(condition_root),
            "--output-dir",
            str(peer_dir),
        ]
        completed = subprocess.run(
            peer_command,
            cwd=str(PROJECT_ROOT),
            env=_local_env(),
            capture_output=True,
            text=True,
            check=False,
        )
        _write_text(condition_root / "logs" / "peer_comparison.stdout.log", completed.stdout or "")
        _write_text(condition_root / "logs" / "peer_comparison.stderr.log", completed.stderr or "")
        if completed.returncode != 0:
            raise RuntimeError(f"Local peer comparison failed with rc={completed.returncode}")
        local_steps.append(
            {
                "name": "peer_comparison",
                "status": "success",
                "api_calls": 0,
                "command": peer_command,
            }
        )
    else:
        local_steps.append(
            {
                "name": "primary_only_no_sy_recomposition",
                "status": "planned",
                "api_calls": 0,
                "source_pipeline_manifest": str(primary_manifest_path),
            }
        )

    peer_comparison = condition_root / "Competitor" / run_key / "peer_comparison_dataset.json"
    synthetic_path = condition_root / "recomposition_source_manifest.json"
    synthetic = {
        "status": "success",
        "run_key": run_key,
        "target": primary.get("target") or {"company_name": company_name},
        "peer": primary.get("peer") or {},
        "request": primary.get("request") or {},
        "source_pipeline_manifest": str(primary_manifest_path),
        "recomposition": {
            "use_sy": False,
            "primary_data_only": True,
            "include_competitor": True,
            "local_only_steps": True,
        },
        "outputs": {
            "strategy_report": str(condition_root / "Strategy" / run_key / "source_anchor.json"),
            "peer_comparison": str(peer_comparison),
        },
    }
    _write_json(synthetic_path, synthetic)
    return synthetic_path, local_steps


def _materialize_no_sy_domain(
    *, domain: str, source: Path, output_root: Path, run_key: str
) -> None:
    if domain == "financial":
        base = output_root / "Financial" / run_key
        verified = base / "agent_pipeline" / "pipeline_verified_financial_report_output.json"
        validation = base / "agent_pipeline" / "pipeline_sy_validation_output.json"
        run_adapter(
            argparse.Namespace(
                domain=domain,
                input=source,
                verified_report=verified,
                validation=validation,
                trace_output=base / "agent_pipeline" / "pipeline_sy_validation_trace.json",
                strategy_report=None,
            )
        )
    elif domain == "news":
        base = output_root / "News" / run_key
        verified = base / "output" / "sy_agent" / "news_agent_verified_handoff.json"
        validation = base / "output" / "sy_agent" / "sy_claim_validations.json"
        run_adapter(
            argparse.Namespace(
                domain=domain,
                input=source,
                verified_report=verified,
                validation=validation,
                trace_output=None,
                strategy_report=None,
            )
        )
    elif domain == "yfinance":
        base = output_root / "Y_Finance" / run_key
        verified = base / "sy_verified_yfinance_report.json"
        validation = base / "yfinance_verified_report.json"
        run_adapter(
            argparse.Namespace(
                domain=domain,
                input=source,
                verified_report=verified,
                validation=validation,
                trace_output=None,
                strategy_report=verified,
            )
        )
    else:
        raise ValueError(domain)
    shutil.copy2(verified, base / "final_report.json")
    shutil.copy2(validation, base / "final_validation.json")


def _preview_final_commands(
    *,
    args: argparse.Namespace,
    condition: AblationCondition,
    condition_root: Path,
    source_manifest: Path,
    company_name: str,
) -> list[list[str]]:
    source = _load_json(source_manifest)
    outputs = source.get("outputs") if isinstance(source.get("outputs"), dict) else {}
    run_key = str(source.get("run_key") or "")
    source_root = Path(str(outputs.get("strategy_report") or "")).expanduser().resolve().parents[2]
    strategy_dir = condition_root / "Strategy" / run_key
    writer_dir = condition_root / "Writer" / run_key
    strategy = [
        sys.executable,
        "-m",
        "Agent_Team.Strategy_Agent.cli",
        "--target-company-name",
        company_name,
        "--target-run-key",
        run_key,
        "--target-financial",
        str(source_root / "Financial" / run_key / "final_report.json"),
        "--target-news",
        str(source_root / "News" / run_key / "final_report.json"),
        "--target-yfinance",
        str(source_root / "Y_Finance" / run_key / "final_report.json"),
        "--output-dir",
        str(strategy_dir),
        "--packet-version",
        "v2",
        "--llm-model",
        args.llm_model,
        "--llm-timeout",
        str(args.llm_timeout),
        "--decision-horizon-profile",
        args.decision_horizon_profile,
        "--semantic-attempts",
        str(args.semantic_attempts),
        "--env-file",
        str(args.env_file.expanduser().resolve()),
        "--experiment-name",
        condition.name,
    ]
    for domain in ("financial", "news", "yfinance"):
        strategy.extend(["--include-domain", domain])
    if "--no-competitor" in condition.flags:
        strategy.append("--no-competitor")
    else:
        strategy.extend(["--peer-comparison", str(outputs.get("peer_comparison") or "")])
    strategy.append("--no-sy")
    if "--primary-data-only" in condition.flags:
        strategy.append("--primary-data-only")
    writer = [
        sys.executable,
        str(PROJECT_ROOT / "src" / "Agent_Team" / "Writer Agent" / "writer_agent.py"),
        "--run-key",
        run_key,
        "--strategy-packet",
        str(strategy_dir / "strategy_compact_packet_v2.json"),
        "--strategy-provenance",
        str(strategy_dir / "strategy_packet_provenance_v2.json"),
        "--strategy-decision",
        str(strategy_dir / "strategy_decision_output_v2.json"),
        "--output-dir",
        str(writer_dir),
        "--env-file",
        str(args.env_file.expanduser().resolve()),
        "--llm-model",
        args.llm_model,
        "--semantic-attempts",
        str(args.semantic_attempts),
    ]
    return [strategy, writer]


def _assert_final_only_usage(manifest_path: Path) -> None:
    manifest = _load_json(manifest_path)
    usage = manifest.get("llm_usage") if isinstance(manifest.get("llm_usage"), dict) else {}
    by_role = usage.get("by_role") if isinstance(usage.get("by_role"), dict) else {}
    target_calls = int((by_role.get("target") or {}).get("observed_logical_calls") or 0)
    peer_calls = int((by_role.get("peer") or {}).get("observed_logical_calls") or 0)
    if target_calls or peer_calls:
        raise RuntimeError(
            f"Unexpected upstream LLM calls: target={target_calls}, peer={peer_calls}"
        )
    if int(usage.get("observed_logical_calls") or 0) != 2:
        raise RuntimeError(
            "Final-stage usage did not contain exactly one Strategy and one Writer logical call."
        )


def _pipeline_root(outputs: dict[str, Any]) -> Path:
    strategy_report = Path(str(outputs.get("strategy_report") or "")).expanduser().resolve()
    if not strategy_report.is_file():
        raise ValueError(f"Strategy report is missing: {strategy_report}")
    return strategy_report.parents[2]


def _pre_sy_paths(root: Path, run_key: str) -> dict[str, Path]:
    return {
        "financial": root / "Financial" / run_key / "agent_pipeline" / "pipeline_financial_analyst_report_output.json",
        "news": root / "News" / run_key / "output" / "news_agent_handoff.json",
        "yfinance": root / "Y_Finance" / run_key / "yfinance_analyst_report.json",
    }


def _find_record(manifest: dict[str, Any], condition: str, replicate: int) -> dict[str, Any] | None:
    for record in manifest.get("runs") or []:
        if (
            isinstance(record, dict)
            and record.get("condition") == condition
            and record.get("replicate") == replicate
        ):
            return record
    return None


def _finalize(manifest: dict[str, Any], suite_root: Path) -> dict[str, Any]:
    summary = build_summary(manifest)
    manifest["status"] = summary["status"]
    manifest["completed_at"] = _utc_now()
    _write_json(suite_root / "ablation_suite_manifest.json", manifest)
    summary = build_summary(manifest)
    _write_json(suite_root / "ablation_summary.json", summary)
    _write_text(suite_root / "ablation_summary.md", render_summary_markdown(summary))
    return summary


def _local_env() -> dict[str, str]:
    environment = os.environ.copy()
    source = str(PROJECT_ROOT / "src")
    current = environment.get("PYTHONPATH", "")
    environment["PYTHONPATH"] = source if not current else source + os.pathsep + current
    return environment


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.expanduser().resolve().open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _load_json(path: Path) -> dict[str, Any]:
    resolved = path.expanduser().resolve()
    payload = json.loads(resolved.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"JSON object required: {resolved}")
    return payload


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _write_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    summary = run_suite(args)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0 if summary.get("status") in {"success", "dry_run"} else 1


if __name__ == "__main__":
    raise SystemExit(main())
